name: Timer
description: Timer
main: me.eduard.timer.Main
version: 1.0
authors: [Eduard]
commands:
  cd:
    description: CoolDown Commando
  dl:
    description: Delay Comando
  tm:
    description: Timer Comando