name: KitPvP
description: Plugin KitPvP
main: net.eduard.kitpvp.Main
version: 1.4
authors: [Eduard]
depend: [EduardAPI]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  resetkit:
    description: Resetar seu Kit
  kit:
    description: Pegar um Kit